---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver-poc
  labels:
    app: apiserver-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver-poc
  template:
    metadata:
      labels:
        app: apiserver-poc
    spec:
      serviceAccountName: apiserver-poc
      containers:
      - name: apiserver-poc
        image: docker.io/tlebreux/apiserver-poc:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver-poc
spec:
  selector:
    app: apiserver-poc
  ports:
  - protocol: TCP
    port: 9443
    targetPort: 9443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiserver-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiserver-poc
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiserver-poc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apiserver-poc
subjects:
- kind: ServiceAccount
  name: apiserver-poc
  namespace: default
